services:
  kali-ctf:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kali-ctf
    tty: true
    stdin_open: true
    volumes:
      - ./workspace:/root/ctf:rw,z
      - ./.bash_history:/root/.bash_history:rw,z

    network_mode: host
    restart: unless-stopped
